debug: true

spring:
  devtools:
    livereload:
      enabled: true

  jpa:
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create-drop

    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:myblog
    username: sa
    password: password
